name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # 允许推送到 GitHub Packages (GHCR)

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from Dockerfile
        id: version
        run: |
          VERSION=$(grep -E '^ARG VERSION=' Dockerfile | cut -d'=' -f2)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Detected VERSION=$VERSION"

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}-build${{ github.run_number }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ionic:latest
            ghcr.io/${{ github.repository_owner }}/ionic:${{ env.VERSION }}-build${{ github.run_number }}
